namespace: ernstov
go-blank-app-10:
    - defines: runnable
      inherits: infinity/base
    - variables:
        password:
            env: ADMIN_PASSWORD
            type: string
            value: not-set
        port:
            env: PORT
            type: int
            value: 8080
        user:
            env: ADMIN_USERNAME
            type: string
            value: admin
    - services:
        webserver:
            port: 8080
            protocol: tcp
    - container:
        build: .
